"""
SmartPulse AI - Financial Data Masking Utility

Purpose:
    This module provides functionality to mask sensitive business financial metrics (Revenue, 
    Expenses, Profit) and region names before they are sent to the external Anthropic Claude API.
    Once the AI generates plain-English insights on the masked data, this utility can unmask
    the generated text to restore the original region names and currency values.

Role in Agent System:
    The Insight Generator Agent uses this utility before constructing the prompt for the 
    Claude API. It ensures that the external LLM never receives raw SME financial figures,
    addressing critical enterprise privacy requirements.

Design Decisions:
    - Region Pseudonymization: Maps real region names (e.g., "North") to standard aliases 
      (e.g., "Region Alpha") to hide geographical details.
    - Financial Scaling: Scales absolute dollar values by a base scaling factor (1.0 = baseline)
      or maps them to percentage changes, preserving the relative statistical properties 
      (e.g., a 300% spike or 80% drop) so the AI can perform accurate root-cause analysis.
    - Text Replacer: Uses simple regex/string replacements to unmask regions and metrics in 
      the AI-generated text.

Agent Communication Pattern:
    1. Orchestrator passes raw anomalies to Insight Generator.
    2. Insight Generator calls FinancialDataMasker.mask_anomalies().
    3. Insight Generator sends masked data to Claude.
    4. Claude responds using the masked terms (e.g., "Region Alpha's revenue dropped by 80%").
    5. Insight Generator calls FinancialDataMasker.unmask_text() to convert it back to 
       "West's revenue dropped by 80%" before returning it to the Orchestrator.
"""

import re
from typing import Dict, List, Any, Tuple

# Mapping of real regions to pseudonymized names
REGION_MAP = {
    "North": "Region_Alpha",
    "South": "Region_Beta",
    "East": "Region_Gamma",
    "West": "Region_Delta",
    "Central": "Region_Epsilon"
}

# Inverse mapping for unmasking
REVERSE_REGION_MAP = {v: k for k, v in REGION_MAP.items()}

# Standard baselines used to scale values into relative ratios (relative to 1.0)
REGIONAL_BASELINES = {
    "North": 30000.0,
    "South": 25000.0,
    "East": 28000.0,
    "West": 22000.0,
    "Central": 18000.0
}

class FinancialDataMasker:
    """
    Handles masking of sensitive data (anomalies) and unmasking of AI responses.
    """
    
    @staticmethod
    def mask_anomalies(anomalies: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Masks a list of anomaly records, changing regions to pseudonyms and
        scaling absolute currency values to relative units.
        
        Args:
            anomalies: List of dictionaries containing raw anomaly data.
            
        Returns:
            A list of masked dictionaries ready for AI inspection.
        """
        masked_list = []
        for anomaly in anomalies:
            region = anomaly.get("Region", "Unknown")
            date = anomaly.get("Date", "Unknown")
            raw_rev = anomaly.get("Revenue", 0.0)
            raw_exp = anomaly.get("Expenses", 0.0)
            raw_prof = anomaly.get("Profit", 0.0)
            anomaly_type = anomaly.get("AnomalyType", "Unknown")
            
            # Map region to pseudonym
            masked_region = REGION_MAP.get(region, f"Region_{region}")
            
            # Scale financials relative to region baseline
            baseline = REGIONAL_BASELINES.get(region, 20000.0)
            
            # Relative revenue and expenses (e.g. 0.20 instead of $4,400)
            rel_rev = round(raw_rev / baseline, 4)
            rel_exp = round(raw_exp / baseline, 4)
            rel_prof = round(raw_prof / baseline, 4)
            
            masked_record = {
                "Date": date,
                "Region": masked_region,
                "RelativeRevenue": f"{rel_rev * 100:.1f}% of baseline",
                "RelativeExpenses": f"{rel_exp * 100:.1f}% of baseline",
                "RelativeProfit": f"{rel_prof * 100:.1f}% of baseline",
                "AnomalyType": anomaly_type,
                "SeverityScore": anomaly.get("SeverityScore", 0.0)
            }
            masked_list.append(masked_record)
            
        return masked_list

    @staticmethod
    def unmask_text(masked_text: str) -> str:
        """
        Replaces pseudonymized regions and scaled term placeholders back into
        their original readable counterparts.
        
        Args:
            masked_text: Plain-text output generated by the AI.
            
        Returns:
            Unmasked text suitable for displaying to the business owner.
        """
        unmasked = masked_text
        
        # Replace pseudonyms with original region names
        # Sort keys by length descending to prevent partial replacement if any name overlaps
        for mask_name, real_name in sorted(REVERSE_REGION_MAP.items(), key=lambda x: len(x[0]), reverse=True):
            # Case insensitive and word boundary replacement
            pattern = re.compile(r'\b' + re.escape(mask_name) + r'\b', re.IGNORECASE)
            unmasked = pattern.sub(real_name, unmasked)
            
        return unmasked
