"""
SmartPulse AI - End-to-End Integration Test Runner

Purpose:
    This script performs end-to-end execution of the SmartPulse AI multi-agent workflow
    using the sample sales CSV file. It allows testing and verification of the agents'
    behavior in an isolated environment without starting the web server.

Role in Agent System:
    - Orchestration: Instantiates the Orchestrator and triggers the workflow.
    - Data Monitor: Runs Isolation Forest anomaly detection on data/sample_sales.csv.
    - Insight Generator: Calls Claude API to create plain-English audit report.
    - Alert Agent: Executes mock email drafting and logs it to backend/db/alerts.json.

Design Decisions:
    - Command Line Feedback: Prints real-time streaming progress logs generated by the agents.
    - Post-Execution Validation: Displays a summary of detected anomalies, masks sensitive 
      data for profiling, and prints the generated alert record to confirm correct database logging.
"""

import os
import sys
import asyncio
import json

# Add project root to python path to allow imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

# Import components
from backend.agents.orchestrator import Orchestrator
from backend.utils.data_masking import FinancialDataMasker

async def main():
    print("=== SmartPulse AI Agent Integration Test ===")
    csv_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data", "sample_sales.csv"))
    
    if not os.path.exists(csv_path):
        print(f"Error: Sample sales CSV not found at: {csv_path}")
        return
        
    orchestrator = Orchestrator()
    print(f"Triggering Orchestrator for CSV: {csv_path}")
    print("--- Streaming Logs ---")
    
    final_result = None
    async for event_str in orchestrator.run_workflow(csv_path):
        event = json.loads(event_str)
        if event["type"] == "log":
            print(f"[{event['agent'].upper()}] {event['message']}")
        elif event["type"] == "result":
            final_result = event["data"]
            print("\n--- Pipeline Completed Event ---")
            print(event["content"])
            
    if final_result:
        anomalies = final_result["anomalies"]
        print(f"\nDetected {len(anomalies)} anomalies:")
        for idx, a in enumerate(anomalies):
            print(f"  {idx+1}. Region: {a['Region']}, Date: {a['Date']}, Type: {a['AnomalyType']}")
            print(f"     Revenue: ${a['Revenue']:.2f}, Expenses: ${a['Expenses']:.2f}, Profit: ${a['Profit']:.2f}")
            print(f"     Severity Score: {a['SeverityScore']}, Z-Score Rev: {a['ZScoreRevenue']}, Z-Score Exp: {a['ZScoreExpenses']}")
            
        print("\nMasked Data Profiling (First Anomaly Example):")
        masked = FinancialDataMasker.mask_anomalies(anomalies[:1])
        print(json.dumps(masked, indent=2))
        
        print("\nEmail Alert Log Status:")
        print(json.dumps(final_result["latest_alert"], indent=2))

if __name__ == "__main__":
    asyncio.run(main())
